### PR TITLE
Add method to get tensorflow and its dependencies in build.rs, useful for using the crate as a git dependency

### LINKED ISSUE #11: Repo cant be used as a git depdendency
Not sure if the build script can be more generalized, but if you try to patch the repo and override tfmicro in your cargo toml with your git branch, it fails

```bash
error: failed to run custom build command for `tfmicro v0.1.0 (https://github.com/jacobrosenthal/tfmicro.git?branch=broken#e310699f)`

Caused by:
  process didn't exit successfully: `/home/jacob/Downloads/atsamd/boards/pygamer/target/release/build/tfmicro-14a54307ceb02d43/build-script-build` (exit code: 101)
  --- stdout
  Running bindgen
  Setting bindgen to cross compile to thumbv7em-none-eabihf
  OPT_LEVEL = Some("3")
  TARGET = Some("thumbv7em-none-eabihf")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_thumbv7em-none-eabihf = None
  CC_thumbv7em_none_eabihf = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_thumbv7em-none-eabihf = None
  CFLAGS_thumbv7em_none_eabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("dsp,mclass,thumb-mode,v5te,v6,v6k,v6t2,v7")
  OPT_LEVEL = Some("3")
  TARGET = Some("thumbv7em-none-eabihf")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_thumbv7em-none-eabihf = None
  CXX_thumbv7em_none_eabihf = None
  TARGET_CXX = None
  CXX = None
  CROSS_COMPILE = None
  CXXFLAGS_thumbv7em-none-eabihf = None
  CXXFLAGS_thumbv7em_none_eabihf = None
  TARGET_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("dsp,mclass,thumb-mode,v5te,v6,v6k,v6t2,v7")

  --- stderr
  clang version 10.0.0-4ubuntu1 
  Target: thumbv7em-none-unknown-eabihf
  Thread model: posix
  InstalledDir: 
  ignoring nonexistent directory "/home/jacob/.cargo/git/checkouts/tfmicro-a2e3c4288cbcca64/e310699/submodules/tensorflow/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include"
  ignoring nonexistent directory "/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../arm-none-eabi/include/c++/v1"
  ignoring nonexistent directory "lib/clang/10.0.0/include"
  ignoring nonexistent directory "/usr/lib/lib/clang/10.0.0/include"
  ignoring duplicate directory "/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/include"
    as it is a non-system directory that duplicates a system directory
  #include "..." search starts here:
  #include <...> search starts here:
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/include/c++/9.3.1
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/include/c++/9.3.1/arm-none-eabi/thumb/v7e-m+fp/hard
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/include/c++/9.3.1/backward
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/include
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/include-fixed
   /home/jacob/.cargo/git/checkouts/tfmicro-a2e3c4288cbcca64/e310699/submodules/tensorflow
   /usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/include
  End of search list.
  /home/jacob/.cargo/git/checkouts/tfmicro-a2e3c4288cbcca64/e310699/submodules/tensorflow/tensorflow/lite/micro/micro_interpreter.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
  /home/jacob/.cargo/git/checkouts/tfmicro-a2e3c4288cbcca64/e310699/submodules/tensorflow/tensorflow/lite/micro/micro_interpreter.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/jacob/.cargo/git/checkouts/tfmicro-a2e3c4288cbcca64/e310699/build.rs:382:33
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

```

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Closes  #11

Fix via @mvniekerk

### CODE REVIEW

**Comment by richardeoin** [comment]
It's already possible to use the crate as a local dependency - in fact the example [does this](https://github.com/Recognition2/tfmicro/blob/master/examples/stm32f0/Cargo.toml#L17). But nice that we can also support use as a git dependency with this PR.

Could you update the make command (and its println!) to [match the documentation](https://github.com/Recognition2/tfmicro/blob/master/DEVELOP.md)? Then we can merge this.

**Comment by jacobrosenthal** [comment]
Like this?

**Comment by jacobrosenthal** [comment]
Doesnt seem to like it.

**Comment by richardeoin** [comment]
Yes, it fails because the CI has **already built** that example. And it built it as superuser because of some awkwardness with the github environment. So you can't build it again as an ordinary user.

Maybe build.rs should detect when the example has already been built? 

The PR already has a broken attempt at this, but it always evaluates to `true`. Maybe you meant `"submodules/tensorflow/tensorflow/lite/micro/tools/make/downloads/flatbuffers/CONTRIBUTING.md"`?

**Comment by jacobrosenthal** [comment]
Seems fixed

**Comment by richardeoin** [comment]
Thanks!

**Pull request merged**
